### ISSUE TITLE
Credentials for Windows Users

### ISSUE THREAD

**Issue by MrBracey** [kurrik/twittergo#15]
Just to say that the end of line char in the CREDENTIALS file must be in UNIX format (LF and  not CR+LF) otherwise the authentication fails.

**Comment by kurrik** [comment]
Yikes, I've been putting off dealing with this for too long :(   I've been meaning to update the examples to use a common lib for stuff like `LoadCredentials` but it's been on my back burner.

As a quick patch, I added this note to the README so that hopefully it saves someone some debugging time.  Sorry again for the delay!
